### ISSUE TITLE
CheckNode task is deprecated and incorrect

### ISSUE THREAD

**Issue by stevenpollack** [proximacapital/gulp-tasks#22]
```bash
[09:21:21] Error: Invalid Node version. Expected: 14.16.1
. Received: v14.16.1
    at CheckNode (/home/steven/proxima/aqueduct/node_modules/@proxima-oss/gulp-tasks/Src/Tasks/CheckNode.ts:12:14)
    at check-node (/home/steven/proxima/aqueduct/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (/home/steven/proxima/aqueduct/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
````
We assume that `process.version` will have the version number without the prepended `v` but that's a lie.

While we're at it, we should write this as a vanilla JS script so that the preinstall script can run without depending on the `check-node` task from actually existing in a gulpfile.

**Comment by stevenpollack** [comment]
closed with #23
